# -*- coding: utf-8 -*-
"""ADS Exp 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14GCFbDvuzonfO52_IWbFTNg2O4KehlVV
"""

import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
df = pd.read_csv('ADS_dataset.csv')

df.head()

df['RainToday'].value_counts()

df = df.fillna(df.mean())
df.head()

df.drop(['Date', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainTomorrow'], axis='columns', inplace=True)
df['RainToday'] = df['RainToday'].fillna('No')
df.head()

"""**Count Plot**"""

# count plot on single categorical variable
sns.countplot(x ='RainToday', data = df)
plt.show()

"""**Scatter Plot**"""

sns.scatterplot(x='MinTemp', y='MaxTemp', hue='RainToday', data=df)
plt.title('Scatter Plot of Examples by Class Label')
plt.xlabel('Minimum Temp')
plt.ylabel('Maximum Temp')
plt.show()

#encoding
df.RainToday = df.RainToday.map({'Yes': 1, 'No': 0})
df.head()

inputs = df.drop('RainToday',axis='columns')
inputs.head()

from sklearn.preprocessing import MinMaxScaler

#normalize
scaler = MinMaxScaler()
scaler.fit(inputs)
df_normalized = pd.DataFrame(scaler.transform(inputs), columns=inputs.columns)
df_normalized.head()

target = df.RainToday
target.head()

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

X_train, X_test, y_train, y_test = train_test_split(df_normalized, target, test_size=0.3)

clf = KNeighborsClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

from sklearn.metrics import f1_score
f1_before = f1_score(y_test, y_pred)
print("F-Score before SMOTE:", f1_before)

from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy='not majority', k_neighbors=5, random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
clf.fit(X_resampled, y_resampled)

y_pred = clf.predict(X_test)
f1 = f1_score(y_test, y_pred, average= 'weighted')
print("F-Score after SMOTE:", f1)